// Coordinating Actions
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const RECIEVE_PLAYLIST = 'RECIEVE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const ADD_TRACK_TO_PLAYLIST = 'ADD_TRACK_TO_PLAYLIST';
export const UPDATE_PLAYLIST_WITH_NEW_TRACK = 'UPDATE_PLAYLIST_WITH_NEW_TRACK';
export const REMOVE_TRACK_FROM_PLAYLIST = 'REMOVE_TRACK_FROM_PLAYLIST';

// Cache Actions
export const CACHE_PLAYLISTS = 'CACHE_PLAYLISTS';
export const CACHE_SONGS = 'CACHE_SONGS';